Make hostname handling more flexible and add metrics.
m-lab/reboot-service pull request #5
Opened 2019-04-03 10:32 UTC by evfirerob

Since there are multiple ways to specify a hostname to reboot, this change aims to handle to most common ones, i.e. the same we already accept in other tools (such as drac.py).

The following Prometheus metrics have also been added:
- reboot_drac_total{site, machine} is a counter containing the number of reboots
- reboot_drac_duration_seconds is a histogram containing the time it took to reboot a DRAC. Bucket size has been chosen empirically and can probably be improved.

2019-04-05 14:58 UTC, stephen-soltesz requested changes
> *[Reviewable](https://reviewable.io/reviews/m-lab/reboot-service/5)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @evfirerob, @pboothe, and @stephen-soltesz)

___
*[main.go, line 39 at r1](https://reviewable.io/reviews/m-lab/reboot-service/5#-Lbhlw2C8_dlXomAzN96:-Lbhlw2C8_dlXomAzN97:b-7jamle) ([raw file](https://github.com/m-lab/reboot-service/blob/1c9101e143e5730a5f163386312942fb5bc5c071/main.go#L39)):*
> ```Go
> const (
> 	defaultListenAddr = ":8080"
> 	defaultPromPort   = ":8081"
> ```

I suggest using a port in the 9xxx range for prometheus metrics. See for example: https://github.com/prometheus/prometheus/wiki/Default-port-allocations -- I don't think there's any need to register your port b/c this is not a general purpose exporter. 

We might want to consider maintaining our own m-lab list however so we don't go crazy.
___
*[main.go, line 85 at r1](https://reviewable.io/reviews/m-lab/reboot-service/5#-LbhmxytEn-ZUTMUPITw:-LbhmxytEn-ZUTMUPITx:by1mwip) ([raw file](https://github.com/m-lab/reboot-service/blob/1c9101e143e5730a5f163386312942fb5bc5c071/main.go#L85)):*
> ```Go
> 
> 	// Initialize Prometheus server for monitoring.
> 	prometheusx.MustStartPrometheus(*promAddr)
> ```

If you intend to test `main` it may be helpful to `Close` the server returned for the Prom listener also.
___
*[reboot/handler.go, line 20 at r1](https://reviewable.io/reviews/m-lab/reboot-service/5#-Lbhn8657htvmArYmAnW:-Lbhn8657htvmArYmAnX:bf2inqs) ([raw file](https://github.com/m-lab/reboot-service/blob/1c9101e143e5730a5f163386312942fb5bc5c071/reboot/handler.go#L20)):*
> ```Go
> 	metricDRACReboots = promauto.NewCounterVec(
> 		prometheus.CounterOpts{
> 			Name: "reboot_drac_total",
> ```

In this case, I suggest not referencing 'DRAC' specifically b/c that references a specific technology that may not always apply. A suitable generic term could be 'BMC'. `reboot_bmc_total`. If it makes sense, something similar for many variable / function names too. (some operations could be technology-specific of course, like `racadm` commands).
___
*[reboot/handler.go, line 151 at r1](https://reviewable.io/reviews/m-lab/reboot-service/5#-LbhoTto0eOdH7BhKXXK:-LbhoTto0eOdH7BhKXXL:bd50p35) ([raw file](https://github.com/m-lab/reboot-service/blob/1c9101e143e5730a5f163386312942fb5bc5c071/reboot/handler.go#L151)):*
> ```Go
> 
> // splitSiteNode splits a hostname into a [site, node] slice
> func splitSiteNode(hostname string) []string {
> ```

This may be 6-one-half-dozen-the-other: in this case, I might return the values explicitly since there are only two and they have specific meaning, e.g. `func splitSiteNode(hostname string) (string, string, error)  {`

The explicit error makes error handling look more idiomatic. And, the caller can save the returned strings explicitly as `machine, site` for self-describing code.


<!-- Sent from Reviewable.io -->

2019-04-08 14:20 UTC, robertodauria reviewed
> *[Reviewable](https://reviewable.io/reviews/m-lab/reboot-service/5)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @pboothe and @stephen-soltesz)

___
*[main.go, line 39 at r1](https://reviewable.io/reviews/m-lab/reboot-service/5#-Lbhlw2C8_dlXomAzN96:-LbxJR-a-MHzb1cVkNIn:b-896fix) ([raw file](https://github.com/m-lab/reboot-service/blob/1c9101e143e5730a5f163386312942fb5bc5c071/main.go#L39)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

I suggest using a port in the 9xxx range for prometheus metrics. See for example: https://github.com/prometheus/prometheus/wiki/Default-port-allocations -- I don't think there's any need to register your port b/c this is not a general purpose exporter. 

We might want to consider maintaining our own m-lab list however so we don't go crazy.
</blockquote></details>

Done.
___
*[main.go, line 85 at r1](https://reviewable.io/reviews/m-lab/reboot-service/5#-LbhmxytEn-ZUTMUPITw:-LbxJRRb3WSa_WUyJOek:b-896fix) ([raw file](https://github.com/m-lab/reboot-service/blob/1c9101e143e5730a5f163386312942fb5bc5c071/main.go#L85)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

If you intend to test `main` it may be helpful to `Close` the server returned for the Prom listener also.
</blockquote></details>

Done.
___
*[reboot/handler.go, line 20 at r1](https://reviewable.io/reviews/m-lab/reboot-service/5#-Lbhn8657htvmArYmAnW:-LbxJSJ-5L1SZvnqaCHs:b-896fix) ([raw file](https://github.com/m-lab/reboot-service/blob/1c9101e143e5730a5f163386312942fb5bc5c071/reboot/handler.go#L20)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

In this case, I suggest not referencing 'DRAC' specifically b/c that references a specific technology that may not always apply. A suitable generic term could be 'BMC'. `reboot_bmc_total`. If it makes sense, something similar for many variable / function names too. (some operations could be technology-specific of course, like `racadm` commands).
</blockquote></details>

Done.
___
*[reboot/handler.go, line 151 at r1](https://reviewable.io/reviews/m-lab/reboot-service/5#-LbhoTto0eOdH7BhKXXK:-LbxJT077iJA7jIOYAK-:b-896fix) ([raw file](https://github.com/m-lab/reboot-service/blob/1c9101e143e5730a5f163386312942fb5bc5c071/reboot/handler.go#L151)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

This may be 6-one-half-dozen-the-other: in this case, I might return the values explicitly since there are only two and they have specific meaning, e.g. `func splitSiteNode(hostname string) (string, string, error)  {`

The explicit error makes error handling look more idiomatic. And, the caller can save the returned strings explicitly as `machine, site` for self-describing code.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2019-04-08 14:31 UTC, stephen-soltesz approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>  - one typo one suggestion.

> Reviewed 5 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/m-lab/reboot-service/5#-:-LbxM4fm-JPeN9Sew82V:b-rge1la)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @evfirerob, @pboothe, and @stephen-soltesz)

___
*[connector/connector.go, line 18 at r2](https://reviewable.io/reviews/m-lab/reboot-service/5#-LbxKRq6BG9vbQ0hhGQV:-LbxKRq6BG9vbQ0hhGQW:bdk28fr) ([raw file](https://github.com/m-lab/reboot-service/blob/c7df6dbd990f6dfdf6914f783054e55a7cbdd997/connector/connector.go#L18)):*
> ```Go
> const (
> 	// BMCConnection is an SSH connection to the node's BMC
> 	BMCConnection ConnType = 0
> ```

Because Go's default zero value is zero, it can be helpful to define the zero value as an invalid type, e.g. `UnspecifiedConnection`. That way it's easier to trust that when code sees BMCConnection that it is was actually specified rather than an accidental default value. This may not always be what we'd want. In this case I think it could help.
___
*[reboot/handler.go, line 29 at r2](https://reviewable.io/reviews/m-lab/reboot-service/5#-LbxLHWfE9q74ahzQltr:-LbxLHWfE9q74ahzQlts:b-e3guxi) ([raw file](https://github.com/m-lab/reboot-service/blob/c7df6dbd990f6dfdf6914f783054e55a7cbdd997/reboot/handler.go#L29)):*
> ```Go
> 	)
> 	metricBMCRebootTimeHist = promauto.NewHistogram(prometheus.HistogramOpts{
> 		Name:    "reboot_drac_duration_seconds",
> ```

s/drac/bmc/?


<!-- Sent from Reviewable.io -->

2019-04-08 14:56 UTC, robertodauria reviewed
> *[Reviewable](https://reviewable.io/reviews/m-lab/reboot-service/5)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @pboothe and @stephen-soltesz)

___
*[connector/connector.go, line 18 at r2](https://reviewable.io/reviews/m-lab/reboot-service/5#-LbxKRq6BG9vbQ0hhGQV:-LbxRmvk1wqSsdhh74uV:b-896fix) ([raw file](https://github.com/m-lab/reboot-service/blob/c7df6dbd990f6dfdf6914f783054e55a7cbdd997/connector/connector.go#L18)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Because Go's default zero value is zero, it can be helpful to define the zero value as an invalid type, e.g. `UnspecifiedConnection`. That way it's easier to trust that when code sees BMCConnection that it is was actually specified rather than an accidental default value. This may not always be what we'd want. In this case I think it could help.
</blockquote></details>

Done.
___
*[reboot/handler.go, line 29 at r2](https://reviewable.io/reviews/m-lab/reboot-service/5#-LbxLHWfE9q74ahzQltr:-LbxRo34-jWw4P02DuiG:b-896fix) ([raw file](https://github.com/m-lab/reboot-service/blob/c7df6dbd990f6dfdf6914f783054e55a7cbdd997/reboot/handler.go#L29)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

s/drac/bmc/?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2019-04-08 15:41 UTC, merged